---
- hosts: web
  sudo: yes

  tasks:
    - name: add a new user
      user: name=ishikawa

    - name: install libselinux-python
      yum: name=libselinux-python state=latest

    - name: install some indispensable tools
      yum: name={{item}} state=latest
      with_items:
        - vim
        - git
        - unzip

    - name: install apache
      yum: name=httpd state=latest

    - name: start apache and enabled
      service: name=httpd state=started enabled=yes

    - name: on apache
      action: command /sbin/chkconfig httpd on

    - name: Disable iptables
      action: service name=iptables state=stopped enabled=false

    - name: delete httpd root directory in order to create sim link
      action: file dest=/var/www/html state=absent

    - name: create html directory
      file: dest=/vagrant/html owner=vagrant group=vagrant state=directory

    - name: create sim link
      file: src=/vagrant/html dest=/var/www/html owner=vagrant group=vagrant state=link

    - name: install php packages
      yum: name={{item}} state=latest
      with_items:
        - php
        - php-devel
        - php-mbstring
        - php-mysql
      notify:
        - restart apache

    #- name: copy hello.php
    #  copy: src=./hello.php dest=/var/www/html/hello.php owner=vagrant

    - name: install mysql
    #  yum: name=mysql-server state=latest
      yum: name={{item}} state=latest
      with_items:
        - mysql-server
        - MySQL-python

    - name: start mysql and enabled
      service: name=mysqld state=started enabled=yes

    - name: create a database
      mysql_db: name=mydb state=present

    - name: create a user for mydb
      mysql_user: name=dbuser password=dbpassword priv=mydb.*:ALL state=present

    - name: WordPress Download
      get_url: url="https://ja.wordpress.org/wordpress-4.0.1-ja.zip" dest=/tmp

    # Unarchive a file that is already on the remote machine
    - name: unarchive wordpress.zip
      unarchive: src=/tmp/wordpress-4.0.1-ja.zip dest=/vagrant/html copy=no

  handlers:
    - name: restart apache
      service: name=httpd state=restarted

